[package]
name = "sec_chat_client"
resolver = "2"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
lib_sec = { path = "../lib_sec" }
rsa = "*"
dirs = "*"