[package]
resolver = "2"
name = "lib_sec"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rsa = "0.9.6"
bincode = "*"
serde = "*"
thiserror = "*"
dirs = "*"
hex = "*"
tokio = {features = ["full"], version = "*"}